name-template: 'gtui $NEXT_MINOR_VERSION'
tag-template: '$NEXT_MINOR_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'feature'
  - title: 'Improvements'
    labels:
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
change-template: '- $TITLE (#$NUMBER)'
template: |
  # Release $NEXT_MINOR_VERSION
  $CHANGES
exclude-labels:
  - 'skip-release'